[package]
name = "opsgenie-client"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest.workspace = true
url.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
